let lexRU = [
    'Color Guess • сделано littlebear',
    '<img src="play.png" width="34"> Играть',
    '<img src="sets.png" width="34"> Настройки',
    '<img src="back.png" width="24"> Назад',
    '<img src="pause.png" width="24"> Пауза',
    'Уровень',
    'Комбо',
    'Шанс!',
    '<img src="ad.png"> Получить',
    'Нет, спасибо!',
    'Восстановление здоровья',
    'Восстанови все недостающие единицы здоровья!',
    'Супер-комбо',
    'Теперь комбо не прибавляется к полученному количеству очков, а умножается на него! (действует на 5 следующих уровней)',
    'Множитель очков',
    'Ваши текущие очки будут умножены на 5.',
    'Ты проиграл!',
    'Очки:',
    '<img src="again.png" width="18"> Играть снова',
    '<img src="menu.png" width="18"> Меню',
    '<img src="go.png" width="18"> Продолжить',
    'Пауза',
    'Настройки',
    '<img src="lang.png" width="20"> Язык',
    '<img src="ru.png" width="32"> Русский',
    '<img src="link.png" width="20"> Ссылки',
];

let lexEN = [
    'Color Guess • made by littlebear',
    '<img src="play.png" width="34"> Play',
    '<img src="sets.png" width="34"> Settings',
    '<img src="back.png" width="24"> Back',
    '<img src="pause.png" width="24"> Pause',
    'Level',
    'Combo',
    'Chance!',
    '<img src="ad.png"> Get',
    'No, thanks!',
    'Health recovery',
    'Restore all missing health units!',
    'Super-combo',
    'Now the combo is not added to the number of points received, but multiplied by it! (valid for the following 5 levels)',
    'Score multiplier',
    'Your current points will be multiplied by 5.',
    'Game over!',
    'Scores:',
    '<img src="again.png" width="18"> Try again',
    '<img src="menu.png" width="18"> Menu',
    '<img src="go.png" width="18"> Continue',
    'Pause',
    'Settings',
    '<img src="lang.png" width="20"> Language',
    '<img src="en.png" width="32"> English',
    '<img src="link.png" width="20"> Links',
];